token update
astroport-fi/astroport-token-lists pull request #188
Opened 2023-12-29 17:01 UTC by anhdt3107

2023-12-29 17:08 UTC, anhdt310720 commented
it's goood

2023-12-29 17:09 UTC, anhdt310720 approved these changes
its goood

2023-12-29 17:14 UTC, anhdt310720 requested changes
goood

2023-12-30 01:37 UTC, afsardo requested changes
Logo is too big max 150x150, also add only the necessary image.

2023-12-30 02:28 UTC, closed without merging