Update neutron.json
astroport-fi/astroport-token-lists pull request #429
Opened 2024-03-26 17:39 UTC by bigp2519

ATOM1KLFG addition

2024-03-26 21:30 UTC, gustavomauricio requested changes
Missing image file

2024-03-26 21:58 UTC, bigp2519 commented
![ATOM1KLFG](https://github.com/astroport-fi/astroport-token-lists/assets/165068559/aa0703be-f857-47ec-b85f-15eddad7dc1b)

2024-03-26 22:30 UTC, bigp2519 commented
> Missing image file

Hey I have the image in img directory and also added to this thread. Let me know if still an issue.

2024-03-27 06:47 UTC, gustavomauricio approved these changes

2024-03-27 06:47 UTC, merged