Update injective.json
astroport-fi/astroport-token-lists pull request #438
Opened 2024-03-29 11:58 UTC by NBOYDev

![NBOY](https://github.com/astroport-fi/astroport-token-lists/assets/164808529/f5ef8dbd-c8b9-4e4a-8e7c-ec371ebca0d7)

2024-03-30 08:06 UTC, gustavomauricio requested changes
Missing image

2024-03-30 13:09 UTC, NBOYDev commented
Token image

![NBlogo](https://github.com/astroport-fi/astroport-token-lists/assets/164808529/10b5a666-10fc-4fbf-84e7-8c753cf2eaae)

2024-04-02 10:55 UTC, gustavomauricio commented
> Token image
> 
> 
> 
> ![NBlogo](https://github.com/astroport-fi/astroport-token-lists/assets/164808529/10b5a666-10fc-4fbf-84e7-8c753cf2eaae)
> 
> 

It should be staged in git and not part of the PR comments, it won't work otherwise

2024-04-06 16:34 UTC, afsardo approved these changes

2024-04-06 16:34 UTC, merged