replace logo
astroport-fi/astroport-token-lists pull request #477
Opened 2024-05-24 14:46 UTC by bigp2519

2024-05-26 17:50 UTC, gustavomauricio commented
Could you please fix the merge conflicts so we can merge this one?

2024-05-26 17:51 UTC, gustavomauricio requested changes
Could you please fix the merge conflicts so we can merge this one?

2024-05-26 18:03 UTC, bigp2519 reviewed
replace logo

2024-05-28 21:27 UTC, closed without merging

2024-05-28 21:27 UTC, bigp2519 commented
creating a new one